import { realpathSync, writeFileSync } from 'fs';
import { join } from 'path';
import { minify } from 'terser';
import parser from '../src/parser';

const buildPath = realpathSync(`${__dirname}/../dist`);

const parserSource = parser.generate();

minify(parserSource, { format: { comments: /generated by/ } }).then((minifiedSource) => {
  if (!minifiedSource.code) throw new Error('failed to write source');

  writeFileSync(join(buildPath, 'index.js'), minifiedSource.code);
});
